services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: mern-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mern-frontend
    ports:
      - "4173:4173"
  